### ISSUE TITLE
Audio file not play on earpiece on Samsung (Oreo) device

### ISSUE THREAD

**Issue by MukFlex** [nzkozar/ExoplayerExample#2]
Device - Samsung (Oreo)
Audio file not play  on earpiece 
https://res.cloudinary.com/vip-group/video/upload/v1543406085/GCNRLIX2QO6U.m4a
but  below one is work
https://github.com/nzkozar/ExoplayerExample/blob/master/sample.m4a?raw=true

Can you suggest the reason .

**Comment by nzkozar** [comment]
Not sure. Maybe you can compare the file info of the two files to see if there are any specific differences in the encoding, that could make a difference.

Additionally if you have the option, try playing the file on a lower sdk version. At the time of creating this example, Android Oreo was not out yet, for me to test it.

Let me know if you find anything.
